name: Custom Rom Builder Samsung Galaxy A11/M11

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      GSI:
        description: 'Direct link for GSI image'
        required: true
        default: 'https://sourceforge.net/projects/andyyan-gsi/files/lineage-19.x/lineage-19.1-20230715-UNOFFICIAL-a64_bgN.img.xz'
      ARCH:
        description: 'ARM64 or ARM32?'
        required: true
        default: '32'
      NAME:
        description: 'Rom Name'
        required: true
        default: 'LineageOS_19.1_A11_M11_ARM32_Gapps'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y zip xz-utils unzip p7zip-full wget git

    - name: Preparing Files
      run: |
        wget https://sourceforge.net/projects/a11q/files/a11q.zip
        git clone https://github.com/smiley9000/Custom-Rom-Builder-For-Samsung-Galaxy-A11-M11
        unzip a11q.zip
        rm -f a11q.zip

    - name: Downloading your GSI
      run: |
        mkdir -p ./temp
        wget -O "./temp/gsi_image.img.xz" "${{ github.event.inputs.GSI}}"
        chmod -R 755 ./*

    - name: Building
      run: |
        chmod +x ./arm${{ github.event.inputs.ARCH }}_git
        ./arm${{ github.event.inputs.ARCH }}_git

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.NAME }}
        path: ./zip/Custom_Rom_SDM450.zip
        retention-days: 5
